### ISSUE TITLE
Write test to determine how diesel/postgres handles orphans on delete.

### ISSUE THREAD

**Issue by hgzimmerman** [hgzimmerman/WeekendAtJoes4#46]

**Comment by hgzimmerman** [comment]
Postgres will prevent a delete from occurring if there is a foreign key that references the deleted db row. 

A safe delete should be implemented where possible that will delete children before deleting itself.

**Comment by ethanmdavidson** [comment]
look up "cascading deletes". there should be a way, when you define the foreign key, to tell the db to cascade the deletes, i.e. delete children when parent is deleted. Not sure how to do it through diesel, but the sql will look something like "create foreign key ... on delete cascade;"

**Comment by hgzimmerman** [comment]
I was vaguely aware of this, and yet, I was entirely prepared to manage deletes manually.

Cascading deletes definitely makes sense for Article -> User relations, where if the User is deleted, the article should be deleted.

I wasn't sure if it would scale well to situations where an entity has multiple foreign keys. Eg. A Post has a UserID, ThreadId, and ReplyPostId. If any of those entities is deleted, the post should be removed. I initially saw this as problematic, as I was exposing the delete user operation via an API, which would cause permanent loss of data for anything they created. If a user deletes themselves, I wouldn't want all of their posts or bucket questions to go away.

Instead, over time, I've gravitated to using a tombstone boolean to indicate if an entity is "deleted" or not, instead of explicitly deleting them, keeping their references intact.

Practically speaking, if I only use deletes for tests and instead expose the tombstone flags over the API, cascades for deletes should be optimal.

**Comment by hgzimmerman** [comment]
Yup,
 ```sql
...
  author_id SERIAL REFERENCES users(id) ON DELETE CASCADE,
...
```
Works as expected. Deleting the user row will also remove the article associated with it.

**Comment by hgzimmerman** [comment]
Implemented in commit: https://github.com/hgzimmerman/WeekendAtJoes4/commit/6993f3afad5d1016460a60a9ab20d8a6569cb616
